using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Pokedex.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PokeTypes",
                columns: table => new
                {
                    PokeTypeId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    PokeTypeName = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PokeTypes", x => x.PokeTypeId);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    UserId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.UserId);
                });

            migrationBuilder.CreateTable(
                name: "Pokemon",
                columns: table => new
                {
                    PokemonId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    PokeTypeId = table.Column<int>(nullable: false),
                    Species = table.Column<string>(nullable: true),
                    Description = table.Column<string>(nullable: true),
                    Weight = table.Column<double>(nullable: false),
                    Height = table.Column<double>(nullable: false),
                    ImageMain = table.Column<string>(nullable: true),
                    ImageSprite = table.Column<string>(nullable: true),
                    ImageSilhouette = table.Column<string>(nullable: true),
                    Hp = table.Column<int>(nullable: false),
                    Attack = table.Column<int>(nullable: false),
                    Defense = table.Column<int>(nullable: false),
                    SpAtk = table.Column<int>(nullable: false),
                    SpDef = table.Column<int>(nullable: false),
                    Speed = table.Column<int>(nullable: false),
                    Ability = table.Column<string>(nullable: true),
                    UserId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pokemon", x => x.PokemonId);
                    table.ForeignKey(
                        name: "FK_Pokemon_PokeTypes_PokeTypeId",
                        column: x => x.PokeTypeId,
                        principalTable: "PokeTypes",
                        principalColumn: "PokeTypeId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pokemon_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "UserId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "PokeTypes",
                columns: new[] { "PokeTypeId", "PokeTypeName" },
                values: new object[,]
                {
                    { 1, "Grass" },
                    { 2, "Fire" },
                    { 3, "Water" },
                    { 4, "Bug" },
                    { 5, "Normal" },
                    { 6, "Poison" },
                    { 7, "Electric" },
                    { 8, "Ground" },
                    { 9, "Fighting" },
                    { 10, "Psychic" },
                    { 11, "Rock" },
                    { 12, "Ghost" },
                    { 13, "Ice" },
                    { 14, "Dragon" }
                });

            migrationBuilder.InsertData(
                table: "Pokemon",
                columns: new[] { "PokemonId", "Ability", "Attack", "Defense", "Description", "Height", "Hp", "ImageMain", "ImageSilhouette", "ImageSprite", "PokeTypeId", "SpAtk", "SpDef", "Species", "Speed", "UserId", "Weight" },
                values: new object[,]
                {
                    { 1, "Overgrow", 49, 49, "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.", 0.69999999999999996, 45, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/bulbasaur.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/bulbasaur.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/bulbasaur.gif", 1, 65, 65, "Bulbasaur", 45, null, 6.9000000000000004 },
                    { 41, "Inner Focus", 45, 35, "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.", 0.80000000000000004, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/zubat.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/zubat.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/zubat.gif", 6, 30, 40, "Zubat", 55, null, 7.5 },
                    { 42, "Inner Focus", 80, 70, "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.", 1.6000000000000001, 75, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/golbat.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/golbat.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/golbat.gif", 6, 65, 75, "Golbat", 90, null, 55.0 },
                    { 88, "Stench", 80, 50, "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.", 0.69999999999999996, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/grimer.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/grimer.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/grimer.gif", 6, 40, 50, "Grimer", 25, null, 30.0 },
                    { 89, "Stench", 105, 75, "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.", 1.2, 105, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/muk.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/muk.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/muk.gif", 6, 65, 100, "Muk", 50, null, 30.0 },
                    { 109, "Levitate", 65, 95, "Its body is full of poisonous gas. It floats into garbage dumps, seeking out the fumes of raw, rotting trash.", 0.59999999999999998, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/koffing.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/koffing.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/koffing.gif", 6, 60, 45, "Koffing", 35, null, 1.0 },
                    { 110, "Levitate", 90, 120, "It mixes gases between its two bodies. It’s said that these Pokémon were seen all over the Galar region back in the day.", 1.2, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/weezing.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/weezing.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/weezing.gif", 6, 85, 70, "Weezing", 60, null, 9.5 },
                    { 25, "Static", 55, 30, "When several of these Pokémon gather, their electricity could build and cause lightning storms.", 0.40000000000000002, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/pikachu.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/pikachu.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/pikachu.gif", 7, 50, 50, "Pikachu", 90, null, 6.0 },
                    { 26, "Static", 90, 55, "Its long tail serves as a ground to protect itself from its own high voltage power.", 0.69999999999999996, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/raichu.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/raichu.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/raichu.gif", 7, 90, 90, "Raichu", 100, null, 30.0 },
                    { 81, "Magnet Pull", 35, 70, "Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.", 0.29999999999999999, 25, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/magnemite.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/magnemite.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/magnemite.gif", 7, 95, 55, "Magnemite", 45, null, 6.0 },
                    { 82, "Magnet Pull", 60, 95, "Formed by several Magnemites linked together. They frequently appear when sunspots flare up.", 1.0, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/magneton.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/magneton.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/magneton.gif", 7, 120, 70, "Magneton", 70, null, 60.0 },
                    { 100, "Soundproof", 30, 50, "The identity of this creature is unknown. It has an extreme personality, uses Electric attacks, and at times self-destructs.", 0.5, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/voltorb.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/voltorb.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/voltorb.gif", 7, 55, 55, "Voltorb", 100, null, 10.4 },
                    { 101, "Soundproof", 50, 70, "Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion.", 1.2, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/electrode.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/electrode.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/electrode.gif", 7, 80, 80, "Electrode", 140, null, 66.599999999999994 },
                    { 125, "Static", 83, 57, "If a major power outage occurs, it is certain that this Pokémon has eaten electricity at a power plant.", 1.1000000000000001, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/electabuzz.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/electabuzz.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/electabuzz.gif", 7, 95, 85, "Electabuzz", 105, null, 30.0 },
                    { 135, "Volt Absorb", 65, 60, "If it is angered or startled, the fur all over its body bristles like sharp needles that pierce foes.", 0.80000000000000004, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/jolteon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/jolteon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/jolteon.gif", 7, 110, 95, "Jolteon", 130, null, 24.5 },
                    { 145, "Pressure", 90, 85, "This legendary bird Pokémon is said to appear when the sky turns dark and lightning showers down.", 1.6000000000000001, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/zapdos.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/zapdos.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/zapdos.gif", 7, 125, 90, "Zapdos", 100, null, 52.600000000000001 },
                    { 34, "Poison Point", 92, 77, "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.", 1.3999999999999999, 81, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/nidoking.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/nidoking.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/nidoking.gif", 6, 85, 75, "Nidoking", 85, null, 62.0 },
                    { 27, "Sand Veil", 75, 85, "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.", 0.59999999999999998, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/sandshrew.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/sandshrew.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/sandshrew.gif", 8, 30, 30, "Sandshrew", 40, null, 12.0 },
                    { 33, "Poison Point", 72, 57, "An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom.", 0.90000000000000002, 61, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/nidorino.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/nidorino.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/nidorino.gif", 6, 55, 55, "Nidorino", 65, null, 19.5 },
                    { 31, "Poison Point", 82, 87, "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.", 1.3, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/nidoqueen.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/nidoqueen.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/nidoqueen.gif", 6, 75, 85, "Nidoqueen", 76, null, 60.0 },
                    { 83, "Keen Eye", 65, 55, "The sprig of green onions it holds is its weapon. It is used much like a metal sword.", 0.80000000000000004, 52, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/farfetchd.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/farfetchd.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/farfetchd.gif", 5, 58, 62, "Farfetch'd", 60, null, 15.0 },
                    { 84, "Run Away", 85, 45, "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.", 1.3999999999999999, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/doduo.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/doduo.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/doduo.gif", 5, 35, 35, "Doduo", 75, null, 39.200000000000003 },
                    { 85, "Run Away", 110, 70, "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.", 1.8, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/dodrio.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/dodrio.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/dodrio.gif", 5, 60, 60, "Dodrio", 100, null, 85.200000000000003 },
                    { 108, "Own Tempo", 55, 75, "If this Pokémon’s sticky saliva gets on you and you don’t clean it off, an intense itch will set in. The itch won’t go away, either.", 1.2, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/lickitung.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/lickitung.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/lickitung.gif", 5, 60, 75, "Lickitung", 30, null, 65.5 },
                    { 113, "Natural Cure", 5, 5, "The egg Chansey carries is not only delicious but also packed with nutrition. It’s used as a high-class cooking ingredient.", 1.1000000000000001, 250, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/chansey.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/chansey.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/chansey.gif", 5, 35, 105, "Chansey", 50, null, 34.600000000000001 },
                    { 115, "Early Bird", 95, 80, "Although it’s carrying its baby in a pouch on its belly, Kangaskhan is swift on its feet. It intimidates its opponents with quick jabs.", 2.2000000000000002, 105, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/kangaskhan.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/kangaskhan.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/kangaskhan.gif", 5, 40, 80, "Kangaskhan", 90, null, 80.0 },
                    { 128, "Intimidate", 100, 95, "When Tauros begins whipping itself with its tails, it’s a warning that the Pokémon is about to charge with astounding speed.", 1.3999999999999999, 75, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/tauros.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/tauros.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/tauros.gif", 5, 40, 70, "Tauros", 110, null, 88.400000000000006 },
                    { 132, "Limber", 48, 48, "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.", 0.29999999999999999, 48, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/ditto.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/ditto.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/ditto.gif", 5, 48, 48, "Ditto", 48, null, 4.0 },
                    { 133, "Run Away", 55, 50, "It has the ability to alter the composition of its body to suit its surrounding environment.", 0.29999999999999999, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/eevee.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/eevee.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/eevee.gif", 5, 45, 65, "Eevee", 55, null, 6.5 },
                    { 137, "Trace", 60, 70, "State-of-the-art technology was used to create Porygon. It was the first artificial Pokémon to be created via computer programming.", 0.80000000000000004, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/porygon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/porygon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/porygon.gif", 5, 85, 75, "Porygon", 40, null, 36.5 },
                    { 143, "Immunity", 110, 65, "It is not satisfied unless it eats over 880 pounds of food every day. When it is done eating, it goes promptly to sleep.", 2.1000000000000001, 160, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/snorlax.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/snorlax.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/snorlax.gif", 5, 65, 110, "Snorlax", 30, null, 460.0 },
                    { 23, "Intimidate", 60, 44, "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.", 2.0, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/ekans.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/ekans.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/ekans.gif", 6, 40, 40, "Ekans", 55, null, 6.9000000000000004 },
                    { 24, "Intimidate", 85, 69, "It is rumored that the ferocious warning markings on its belly differ from area to area.", 3.5, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/arbok.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/arbok.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/arbok.gif", 6, 65, 65, "Arbok", 80, null, 65.0 },
                    { 29, "Poison Point", 47, 52, "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.", 0.40000000000000002, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/nidoran.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/nidoran.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/nidoran.gif", 6, 40, 40, "Nidoran", 41, null, 7.0 },
                    { 30, "Poison Point", 62, 67, "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.", 0.80000000000000004, 70, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/nidorina.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/nidorina.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/nidorina.gif", 6, 55, 55, "Nidorina", 56, null, 20.0 },
                    { 32, "Poison Point", 57, 40, "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.", 0.5, 46, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/nidoran.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/nidoran.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/nidoran.gif", 6, 40, 40, "Nidoran", 50, null, 9.0 },
                    { 53, "Limber", 70, 60, "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.", 1.0, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/persian.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/persian.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/persian.gif", 5, 65, 65, "Persian", 115, null, 32.0 },
                    { 28, "Sand Veil", 100, 110, "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.", 1.0, 75, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/sandslash.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/sandslash.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/sandslash.gif", 8, 55, 55, "Sandslash", 65, null, 29.5 },
                    { 51, "Sand Veil", 80, 50, "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.", 0.69999999999999996, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/dugtrio.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/dugtrio.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/dugtrio.gif", 8, 50, 70, "Dugtrio", 120, null, 33.299999999999997 },
                    { 74, "Rock Head", 80, 100, "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.", 0.40000000000000002, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/geodude.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/geodude.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/geodude.gif", 11, 30, 30, "Geodude", 20, null, 20.0 },
                    { 75, "Rock Head", 95, 115, "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.", 1.0, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/graveler.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/graveler.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/graveler.gif", 11, 45, 45, "Graveler", 35, null, 105.0 },
                    { 76, "Rock Head", 110, 130, "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.", 1.3999999999999999, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/golem.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/golem.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/golem.gif", 11, 55, 65, "Golem", 45, null, 300.0 },
                    { 95, "Rock Head", 45, 160, "As it digs through the ground, it absorbs many hard objects. This is what makes its body so solid.", 8.8000000000000007, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/onix.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/onix.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/onix.gif", 11, 30, 45, "Onix", 70, null, 210.0 },
                    { 138, "Swift Swim", 40, 100, "An ancient Pokémon that was recovered from a fossil. It swam by cleverly twisting its 10 tentacles about.", 0.40000000000000002, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/omanyte.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/omanyte.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/omanyte.gif", 11, 90, 55, "Omanyte", 35, null, 7.5 },
                    { 139, "Swift Swim", 60, 125, "Its sharp beak rings its mouth. Its shell was too big for it to move freely, so it became extinct.", 1.0, 70, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/omastar.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/omastar.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/omastar.gif", 11, 115, 70, "Omastar", 55, null, 35.0 },
                    { 140, "Swift Swim", 80, 90, "A Pokémon that was recovered from a fossil. It used the eyes on its back while hiding on the seafloor.", 0.5, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/kabuto.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/kabuto.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/kabuto.gif", 11, 55, 45, "Kabuto", 55, null, 11.5 },
                    { 141, "Swift Swim", 115, 105, "A slim and fast swimmer. It sliced its prey with its sharp sickles and drank the body fluids.", 1.3, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/kabutops.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/kabutops.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/kabutops.gif", 11, 65, 70, "Kabutops", 80, null, 40.5 },
                    { 142, "Rock Head", 105, 65, "A savage Pokémon that died out in ancient times. It was resurrected using DNA taken from amber.", 1.8, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/aerodactyl.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/aerodactyl.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/aerodactyl.gif", 11, 60, 75, "Aerodactyl", 130, null, 59.0 },
                    { 92, "Levitate", 35, 30, "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.", 1.3, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/gastly.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/gastly.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/gastly.gif", 12, 100, 35, "Gastly", 80, null, 0.10000000000000001 },
                    { 93, "Levitate", 50, 45, "Its tongue is made of gas. If licked, its victim starts shaking constantly until death eventually comes.", 1.6000000000000001, 45, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/haunter.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/haunter.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/haunter.gif", 12, 115, 55, "Haunter", 95, null, 0.10000000000000001 },
                    { 94, "Levitate", 65, 60, "On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.", 1.5, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/gengar.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/gengar.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/gengar.gif", 12, 130, 75, "Gengar", 110, null, 40.5 },
                    { 124, "Oblivious", 50, 35, "Appears to move to a rhythm of its own, as if it were dancing. It wiggles its hips as it walks.", 1.3999999999999999, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/jynx.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/jynx.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/jynx.gif", 13, 115, 95, "Jynx", 95, null, 40.600000000000001 },
                    { 144, "Pressure", 85, 100, "A legendary bird Pokémon. It freezes water that is contained in winter air and makes it snow.", 1.7, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/articuno.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/articuno.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/articuno.gif", 13, 95, 125, "Articuno", 85, null, 55.399999999999999 },
                    { 147, "Shed Skin", 64, 45, "Long thought to be a myth, this Pokémon’s existence was only recently confirmed by a fisherman who caught one.", 1.8, 41, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/dratini.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/dratini.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/dratini.gif", 14, 50, 50, "Dratini", 50, null, 3.2999999999999998 },
                    { 151, "Pressure", 100, 100, "When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.", 0.40000000000000002, 100, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/mew.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/mew.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/mew.gif", 10, 100, 100, "Mew", 100, null, 4.0 },
                    { 50, "Sand Veil", 55, 25, "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.", 0.20000000000000001, 10, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/diglett.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/diglett.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/diglett.gif", 8, 35, 45, "Diglett", 95, null, 0.80000000000000004 },
                    { 150, "Pressure", 110, 90, "Its DNA is almost the same as Mew’s. However, its size and disposition are vastly different.", 2.0, 106, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/mewtwo.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/mewtwo.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/mewtwo.gif", 10, 154, 90, "Mewtwo", 130, null, 122.0 },
                    { 97, "Insomnia", 73, 70, "Hypno, a Hypnosis Pokémon. It carries a pendulum-like device and performs hypnotic attacks.", 1.6000000000000001, 85, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/hypno.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/hypno.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/hypno.gif", 10, 73, 115, "Hypno", 67, null, 75.599999999999994 },
                    { 104, "Rock Head", 50, 95, "When the memory of its departed mother brings it to tears, its cries echo mournfully within the skull it wears on its head.", 0.40000000000000002, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/cubone.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/cubone.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/cubone.gif", 8, 40, 50, "Cubone", 35, null, 6.5 },
                    { 105, "Rock Head", 80, 110, "This Pokémon overcame its sorrow to evolve a sturdy new body. Marowak faces its opponents bravely, using a bone as a weapon.", 1.0, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/marowak.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/marowak.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/marowak.gif", 8, 50, 80, "Marowak", 45, null, 45.0 },
                    { 111, "Lightningrod", 85, 95, "Strong, but not too bright, this Pokémon can shatter even a skyscraper with its charging tackles.", 1.0, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/rhyhorn.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/rhyhorn.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/rhyhorn.gif", 8, 30, 30, "Rhyhorn", 25, null, 115.0 },
                    { 112, "Lightningrod", 130, 120, "It begins walking on its hind legs after evolution. It can punch holes through boulders with its horn.", 1.8999999999999999, 105, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/rhydon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/rhydon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/rhydon.gif", 8, 45, 45, "Rhydon", 40, null, 120.0 },
                    { 56, "Vital Spirit", 80, 35, "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.", 0.5, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/mankey.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/mankey.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/mankey.gif", 9, 35, 45, "Mankey", 70, null, 28.0 },
                    { 57, "Vital Spirit", 105, 60, "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.", 1.0, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/primeape.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/primeape.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/primeape.gif", 9, 60, 70, "Primeape", 95, null, 32.0 },
                    { 66, "Guts", 80, 50, "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.", 0.80000000000000004, 70, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/machop.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/machop.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/machop.gif", 9, 35, 35, "Machop", 35, null, 19.5 },
                    { 67, "Guts", 100, 70, "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.", 1.5, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/machoke.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/machoke.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/machoke.gif", 9, 50, 60, "Machoke", 45, null, 70.5 },
                    { 68, "Guts", 130, 80, "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.", 1.6000000000000001, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/machamp.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/machamp.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/machamp.gif", 9, 65, 85, "Machamp", 55, null, 130.0 },
                    { 106, "Limber", 120, 53, "This amazing Pokémon has an awesome sense of balance. It can kick in succession from any position.", 1.5, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/hitmonlee.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/hitmonlee.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/hitmonlee.gif", 9, 35, 110, "Hitmonlee", 87, null, 49.799999999999997 },
                    { 107, "Keen Eye", 105, 79, "Its punches slice the air. They are launched at such high speed, even a slight graze could cause a burn.", 1.3999999999999999, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/hitmonchan.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/hitmonchan.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/hitmonchan.gif", 9, 35, 110, "Hitmonchan", 76, null, 50.200000000000003 },
                    { 63, "Synchronize", 20, 15, "Using its ability to read minds, it will identify impending danger and Teleport to safety.", 0.90000000000000002, 25, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/abra.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/abra.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/abra.gif", 10, 105, 55, "Abra", 90, null, 19.5 },
                    { 64, "Synchronize", 35, 30, "It emits special alpha waves from its body that induce headaches just by being close by.", 1.3, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/kadabra.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/kadabra.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/kadabra.gif", 10, 120, 70, "Kadabra", 105, null, 56.5 },
                    { 65, "Synchronize", 50, 45, "Its brain can outperform a super-computer. Its intelligence quotient is said to be 5,000.", 1.5, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/alakazam.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/alakazam.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/alakazam.gif", 10, 135, 85, "Alakazam", 120, null, 48.0 },
                    { 96, "Insomnia", 48, 45, "If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past.", 1.0, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/drowzee.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/drowzee.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/drowzee.gif", 10, 43, 90, "Drowzee", 42, null, 32.399999999999999 },
                    { 122, "Soundproof", 45, 65, "The broadness of its hands may be no coincidence—many scientists believe its palms became enlarged specifically for pantomiming.", 1.3, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/mrmime.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/mrmime.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/mrmime.gif", 10, 100, 120, "Mr. Mime", 90, null, 54.5 },
                    { 148, "Shed Skin", 84, 65, "According to a witness, its body was surrounded by a strange aura that gave it a mystical look.", 4.0, 61, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/dragonair.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/dragonair.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/dragonair.gif", 14, 70, 70, "Dragonair", 70, null, 16.5 },
                    { 52, "Pickup", 45, 35, "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.", 0.40000000000000002, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/meowth.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/meowth.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/meowth.gif", 5, 40, 40, "Meowth", 90, null, 4.2000000000000002 },
                    { 39, "Cute Charm", 45, 20, "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.", 0.5, 115, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/jigglypuff.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/jigglypuff.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/jigglypuff.gif", 5, 45, 25, "Jigglypuff", 20, null, 5.5 },
                    { 78, "Run Away", 100, 70, "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it.", 1.7, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/rapidash.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/rapidash.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/rapidash.gif", 2, 80, 80, "Rapidash", 105, null, 95.0 },
                    { 126, "Flame Body", 95, 57, "Born in an active volcano. Its body is always cloaked in flames, so it looks like a big ball of fire.", 1.3, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/magmar.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/magmar.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/magmar.gif", 2, 100, 85, "Magmar", 93, null, 44.5 },
                    { 136, "Flash Fire", 130, 60, "Once it has stored up enough heat, this Pokémon’s body temperature can reach up to 1,700 degrees Fahrenheit.", 0.90000000000000002, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/flareon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/flareon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/flareon.gif", 2, 95, 110, "Flareon", 65, null, 25.0 },
                    { 146, "Pressure", 100, 90, "A legendary bird Pokémon. As it flaps its flaming wings, even the night sky will turn red.", 2.0, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/moltres.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/moltres.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/moltres.gif", 2, 125, 85, "Moltres", 90, null, 60.0 },
                    { 7, "Torrent", 48, 65, "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.", 0.5, 44, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/squirtle.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/squirtle.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/squirtle.gif", 3, 50, 64, "Squirtle", 43, null, 9.0 },
                    { 8, "Torrent", 63, 80, "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.", 1.0, 59, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/wartortle.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/wartortle.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/wartortle.gif", 3, 65, 80, "Wartortle", 58, null, 22.5 },
                    { 9, "Torrent", 83, 100, "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.", 1.6000000000000001, 79, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/blastoise.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/blastoise.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/blastoise.gif", 3, 85, 105, "Blastoise", 78, null, 85.5 },
                    { 54, "Damp", 52, 48, "While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.", 0.80000000000000004, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/psyduck.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/psyduck.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/psyduck.gif", 3, 65, 50, "Psyduck", 55, null, 19.600000000000001 },
                    { 55, "Damp", 82, 78, "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.", 1.7, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/golduck.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/golduck.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/golduck.gif", 3, 95, 80, "Golduck", 85, null, 76.599999999999994 },
                    { 60, "Water Absorb", 50, 40, "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.", 0.59999999999999998, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/poliwag.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/poliwag.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/poliwag.gif", 3, 40, 40, "Poliwag", 90, null, 12.4 },
                    { 61, "Water Absorb", 65, 65, "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.", 1.0, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/poliwhirl.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/poliwhirl.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/poliwhirl.gif", 3, 50, 50, "Poliwhirl", 90, null, 20.0 },
                    { 62, "Water Absorb", 85, 95, "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.", 1.3, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/poliwrath.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/poliwrath.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/poliwrath.gif", 3, 70, 90, "Poliwrath", 70, null, 54.0 },
                    { 72, "Clear Body", 40, 35, "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.", 0.90000000000000002, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/tentacool.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/tentacool.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/tentacool.gif", 3, 50, 100, "Tentacool", 70, null, 45.5 },
                    { 73, "Clear Body", 70, 65, "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.", 1.6000000000000001, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/tentacruel.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/tentacruel.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/tentacruel.gif", 3, 80, 120, "Tentacruel", 100, null, 55.0 },
                    { 79, "Oblivious", 65, 65, "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.", 1.2, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/slowpoke.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/slowpoke.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/slowpoke.gif", 3, 40, 40, "Slowpoke", 15, null, 36.0 },
                    { 77, "Run Away", 85, 55, "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.", 1.0, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/ponyta.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/ponyta.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/ponyta.gif", 2, 65, 65, "Ponyta", 90, null, 30.0 },
                    { 80, "Oblivious", 75, 110, "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left over scraps.", 1.6000000000000001, 95, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/slowbro.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/slowbro.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/slowbro.gif", 3, 100, 80, "Slowbro", 30, null, 78.5 },
                    { 59, "Intimidate", 110, 80, "A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings.", 1.8999999999999999, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/arcanine.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/arcanine.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/arcanine.gif", 2, 100, 80, "Arcanine", 95, null, 155.0 },
                    { 38, "Flash Fire", 76, 75, "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.", 1.1000000000000001, 73, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/ninetales.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/ninetales.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/ninetales.gif", 2, 81, 100, "Ninetales", 100, null, 19.899999999999999 },
                    { 2, "Overgrow", 62, 63, "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", 1.0, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/ivysaur.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/ivysaur.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/ivysaur.gif", 1, 80, 80, "Ivysaur", 60, null, 13.0 },
                    { 3, "Overgrow", 82, 83, "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.", 2.0, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/venusaur.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/venusaur.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/venusaur.gif", 1, 100, 100, "Venusaur", 80, null, 100.0 },
                    { 43, "Chlorophyll", 50, 55, "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.", 0.5, 45, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/oddish.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/oddish.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/oddish.gif", 1, 75, 65, "Oddish", 30, null, 5.4000000000000004 },
                    { 44, "Chlorophyll", 65, 70, "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.", 0.80000000000000004, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/gloom.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/gloom.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/gloom.gif", 1, 85, 75, "Gloom", 40, null, 8.5999999999999996 },
                    { 45, "Chlorophyll", 80, 85, "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.", 1.2, 75, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/vileplume.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/vileplume.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/vileplume.gif", 1, 100, 90, "Vileplume", 50, null, 18.600000000000001 },
                    { 69, "Chlorophyll", 75, 35, "A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture.", 0.69999999999999996, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/bellsprout.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/bellsprout.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/bellsprout.gif", 1, 70, 30, "Bellsprout", 40, null, 4.0 },
                    { 70, "Chlorophyll", 90, 50, "It spits out PoisonPowder to immobilize the enemy and then finishes it with a spray of Acid.", 1.0, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/weepinbell.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/weepinbell.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/weepinbell.gif", 1, 85, 45, "Weepinbell", 55, null, 6.4000000000000004 },
                    { 71, "Chlorophyll", 105, 65, "Said to live in huge colonies deep in jungles, although no one has ever returned from there.", 1.7, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/victreebel.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/victreebel.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/victreebel.gif", 1, 100, 60, "Victreebel", 70, null, 15.5 },
                    { 102, "Chlorophyll", 40, 80, "Though it may look like it’s just a bunch of eggs, it’s a proper Pokémon. Exeggcute communicates with others of its kind via telepathy, apparently.", 0.40000000000000002, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/exeggcute.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/exeggcute.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/exeggcute.gif", 1, 60, 45, "Exeggcute", 40, null, 2.5 },
                    { 103, "Chlorophyll", 95, 85, "Each of Exeggutor’s three heads is thinking different thoughts. The three don’t seem to be very interested in one another.", 2.0, 95, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/exeggutor.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/exeggutor.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/exeggutor.gif", 1, 125, 65, "Exeggutor", 55, null, 120.0 },
                    { 114, "Chlorophyll", 55, 115, "Hidden beneath a tangle of vines that grows nonstop even if the vines are torn off, this Pokémon’s true appearance remains a mystery.", 1.0, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/tangela.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/tangela.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/tangela.gif", 1, 100, 40, "Tangela", 60, null, 35.0 },
                    { 4, "Blaze", 52, 43, "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.", 0.59999999999999998, 39, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/charmander.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/charmander.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/charmander.gif", 2, 60, 50, "Charmander", 65, null, 8.5 },
                    { 5, "Blaze", 64, 58, "When it swings its burning tail, it elevates the temperature to unbearably high levels.", 1.1000000000000001, 58, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/charmeleon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/charmeleon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/charmeleon.gif", 2, 80, 65, "Charmeleon", 80, null, 19.0 },
                    { 6, "Blaze", 84, 78, "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.", 1.7, 78, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/charizard.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/charizard.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/charizard.gif", 2, 109, 85, "Charizard", 100, null, 90.5 },
                    { 37, "Flash Fire", 41, 40, "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.", 0.59999999999999998, 38, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/vulpix.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/vulpix.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/vulpix.gif", 2, 50, 65, "Vulpix", 65, null, 9.9000000000000004 },
                    { 58, "Intimidate", 70, 45, "Very protective of its territory. It will bark and bite to repel intruders from its space.", 0.69999999999999996, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/growlithe.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/growlithe.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/growlithe.gif", 2, 70, 50, "Growlithe", 60, null, 19.0 },
                    { 40, "Cute Charm", 70, 45, "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.", 1.0, 140, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/wigglytuff.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/wigglytuff.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/wigglytuff.gif", 5, 75, 50, "Wigglytuff", 45, null, 12.0 },
                    { 86, "Thick Fat", 45, 55, "The protruding horn on its head is very hard. It is used for bashing through thick ice.", 1.1000000000000001, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/seel.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/seel.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/seel.gif", 3, 45, 70, "Seel", 45, null, 90.0 },
                    { 90, "Shell Armor", 65, 100, "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.", 0.29999999999999999, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/shellder.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/shellder.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/shellder.gif", 3, 45, 25, "Shellder", 40, null, 4.0 },
                    { 46, "Effect Spore", 70, 55, "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.", 0.29999999999999999, 35, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/paras.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/paras.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/paras.gif", 4, 45, 55, "Paras", 25, null, 5.4000000000000004 },
                    { 47, "Effect Spore", 95, 80, "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.", 1.0, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/parasect.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/parasect.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/parasect.gif", 4, 60, 80, "Parasect", 30, null, 29.5 },
                    { 48, "Compoundeyes", 55, 50, "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.", 1.0, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/venonat.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/venonat.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/venonat.gif", 4, 40, 55, "Venonat", 45, null, 30.0 },
                    { 49, "Shield Dust", 65, 60, "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.", 1.5, 70, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/venomoth.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/venomoth.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/venomoth.gif", 4, 90, 75, "Venomoth", 90, null, 12.5 },
                    { 123, "Swarm", 110, 80, "As Scyther fights more and more battles, its scythes become sharper and sharper. With a single slice, Scyther can fell a massive tree.", 1.5, 70, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/scyther.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/scyther.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/scyther.gif", 4, 55, 80, "Scyther", 105, null, 56.0 },
                    { 127, "Hyper Cutter", 125, 100, "These Pokémon judge one another based on pincers. Thicker, more impressive pincers make for more popularity with the opposite gender.", 1.5, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/pinsir.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/pinsir.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/pinsir.gif", 4, 55, 70, "Pinsir", 85, null, 55.0 },
                    { 16, "Keen Eye", 45, 40, "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.", 0.29999999999999999, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/pidgey.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/pidgey.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/pidgey.gif", 5, 35, 35, "Pidgey", 56, null, 1.8 },
                    { 17, "Keen Eye", 60, 55, "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.", 1.1000000000000001, 63, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/pidgeotto.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/pidgeotto.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/pidgeotto.gif", 5, 50, 60, "Pidgeotto", 71, null, 30.0 }
                });

            migrationBuilder.InsertData(
                table: "Pokemon",
                columns: new[] { "PokemonId", "Ability", "Attack", "Defense", "Description", "Height", "Hp", "ImageMain", "ImageSilhouette", "ImageSprite", "PokeTypeId", "SpAtk", "SpDef", "Species", "Speed", "UserId", "Weight" },
                values: new object[,]
                {
                    { 18, "Keen Eye", 80, 75, "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.", 1.5, 83, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/pidgeot.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/pidgeot.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/pidgeot.gif", 5, 70, 70, "Pidgeot", 91, null, 39.5 },
                    { 19, "Run Away", 56, 35, "Bites anything when it attacks. Small and very quick, it is a common sight in many places.", 0.29999999999999999, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/rattata.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/rattata.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/rattata.gif", 5, 25, 25, "Rattata", 72, null, 3.5 },
                    { 20, "Run Away", 81, 60, "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.", 0.69999999999999996, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/raticate.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/raticate.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/raticate.gif", 5, 50, 50, "Raticate", 97, null, 18.5 },
                    { 21, "Keen Eye", 60, 30, "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.", 0.29999999999999999, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/spearow.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/spearow.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/spearow.gif", 5, 31, 31, "Spearow", 70, null, 2.0 },
                    { 22, "Keen Eye", 90, 65, "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.", 1.2, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/fearow.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/fearow.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/fearow.gif", 5, 61, 61, "Fearow", 100, null, 38.0 },
                    { 35, "Cute Charm", 45, 48, "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.", 0.59999999999999998, 70, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/clefairy.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/clefairy.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/clefairy.gif", 5, 60, 65, "Clefairy", 35, null, 7.5 },
                    { 36, "Cute Charm", 70, 73, "A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people.", 1.3, 95, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/clefable.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/clefable.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/clefable.gif", 5, 85, 90, "Clefable", 60, null, 40.0 },
                    { 15, "Swarm", 80, 40, "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.", 1.0, 65, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/beedrill.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/beedrill.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/beedrill.gif", 4, 45, 80, "Beedrill", 75, null, 29.5 },
                    { 87, "Thick Fat", 70, 80, "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.", 1.7, 90, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/dewgong.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/dewgong.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/dewgong.gif", 3, 70, 95, "Dewgong", 70, null, 120.0 },
                    { 14, "Shed Skin", 25, 50, "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.", 0.59999999999999998, 45, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/kakuna.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/kakuna.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/kakuna.gif", 4, 25, 25, "Kakuna", 35, null, 10.0 },
                    { 12, "Compoundeyes", 45, 50, "In battle, it flaps its wings at high speed to release highly toxic dust into the air.", 1.1000000000000001, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/butterfree.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/butterfree.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/butterfree.gif", 4, 80, 80, "Butterfree", 70, null, 32.0 },
                    { 91, "Shell Armor", 90, 180, "Its shell is extremely hard. It cannot be shattered, even with a bomb. The shell opens only when it is attacking.", 1.5, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/cloyster.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/cloyster.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/cloyster.gif", 3, 85, 45, "Cloyster", 70, null, 132.5 },
                    { 98, "Hyper Cutter", 105, 90, "Krabby, the River Crab Pokémon. Living on sandy beaches in burrows it digs, Krabby can grow back its pincers if they break off in battle.", 0.40000000000000002, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/krabby.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/krabby.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/krabby.gif", 3, 25, 25, "Krabby", 50, null, 6.5 },
                    { 99, "Hyper Cutter", 130, 115, "Kingler, the evolved form of Krabby. A Pincer Pokémon whose claws can pinch with the power of 10,000 horsepower.", 1.3, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/kingler.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/kingler.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/kingler.gif", 3, 50, 50, "Kingler", 75, null, 60.0 },
                    { 116, "Swift Swim", 40, 70, "Horsea makes its home in oceans with gentle currents. If this Pokémon is under attack, it spits out pitch-black ink and escapes.", 0.40000000000000002, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/horsea.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/horsea.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/horsea.gif", 3, 70, 25, "Horsea", 60, null, 8.0 },
                    { 117, "Poison Point", 65, 95, "It’s the males that raise the offspring. While Seadra are raising young, the spines on their backs secrete thicker and stronger poison.", 1.2, 55, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/seadra.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/seadra.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/seadra.gif", 3, 95, 45, "Seadra", 85, null, 25.0 },
                    { 118, "Swift Swim", 67, 60, "Its dorsal, pectoral, and tail fins wave elegantly in water. That is why it is known as the Water Dancer.", 0.59999999999999998, 45, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/goldeen.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/goldeen.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/goldeen.gif", 3, 35, 50, "Goldeen", 63, null, 15.0 },
                    { 119, "Swift Swim", 92, 65, "In autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors.", 1.3, 80, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/seaking.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/seaking.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/seaking.gif", 3, 65, 80, "Seaking", 68, null, 39.0 },
                    { 120, "Illuminate", 45, 55, "If you visit a beach at the end of summer, you’ll be able to see groups of Staryu lighting up in a steady rhythm.", 0.80000000000000004, 30, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/staryu.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/staryu.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/staryu.gif", 3, 70, 55, "Staryu", 85, null, 34.5 },
                    { 121, "Illuminate", 75, 85, "This Pokémon has an organ known as its core. The organ glows in seven colors when Starmie is unleashing its potent psychic powers.", 1.1000000000000001, 60, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/starmie.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/starmie.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/starmie.gif", 3, 100, 85, "Starmie", 115, null, 80.0 },
                    { 129, "Swift Swim", 10, 55, "It is virtually worthless in terms of both power and speed. It is the most weak and pathetic Pokémon in the world.", 0.90000000000000002, 20, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/magikarp.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/magikarp.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/magikarp.gif", 3, 15, 20, "Magikarp", 80, null, 10.0 },
                    { 130, "Intimidate", 125, 79, "It has an extremely aggressive nature. The Hyper Beam it shoots from its mouth totally incinerates all targets.", 6.5, 95, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/gyarados.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/gyarados.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/gyarados.gif", 3, 60, 100, "Gyarados", 81, null, 235.0 },
                    { 131, "Water Absorb", 85, 80, "A smart and kindhearted Pokémon, it glides across the surface of the sea while its beautiful song echoes around it", 2.5, 130, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/lapras.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/lapras.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/lapras.gif", 3, 85, 95, "Lapras", 60, null, 220.0 },
                    { 134, "Water Absorb", 65, 60, "When Vaporeon’s fins begin to vibrate, it is a sign that rain will come within a few hours.", 1.0, 130, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/vaporeon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/vaporeon.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/vaporeon.gif", 3, 110, 95, "Vaporeon", 65, null, 29.0 },
                    { 10, "Shield Dust", 30, 35, "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.", 0.29999999999999999, 45, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/caterpie.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/caterpie.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/caterpie.gif", 4, 20, 20, "Caterpie", 45, null, 2.8999999999999999 },
                    { 11, "Shed Skin", 20, 55, "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.", 0.69999999999999996, 50, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/metapod.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/metapod.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/metapod.gif", 4, 25, 25, "Metapod", 30, null, 9.9000000000000004 },
                    { 13, "Shield Dust", 35, 30, "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.", 0.29999999999999999, 40, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/weedle.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/weedle.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/weedle.png", 4, 20, 20, "Weedle", 50, null, 3.2000000000000002 },
                    { 149, "Inner Focus", 134, 95, "It is said that this Pokémon lives somewhere in the sea and that it flies. However, these are only rumors.", 2.2000000000000002, 91, "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/fight/dragonite.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/silhouette/dragonite.png", "https://coding-assets.s3-us-west-2.amazonaws.com/pokemon/sprite/dragonite.gif", 14, 100, 100, "Dragonite", 80, null, 210.0 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Pokemon_PokeTypeId",
                table: "Pokemon",
                column: "PokeTypeId");

            migrationBuilder.CreateIndex(
                name: "IX_Pokemon_UserId",
                table: "Pokemon",
                column: "UserId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Pokemon");

            migrationBuilder.DropTable(
                name: "PokeTypes");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
